### ISSUE TITLE
Words in excluded_words being flagged as typos

### ISSUE THREAD

**Issue by Fdawgs** [TypoCI/spellcheck-action#102]
Hi @MikeRogers0,

Not sure if this is just me configuring it incorrectly.
I'm using the following in my repos, located in `.github/.typo-ci.yml`, with the TypoCI GitHub App (not within a workflow job):

```yml
dictionaries:
    - en
    - en_GB
    - javascript

# Any files/folders we should ignore?
excluded_files:
    - ".github/.typo-ci.yml"
    - "node_modules/**/*"
    - "yarn.lock"

# Any typos we should ignore?
excluded_words:
    - fastify
    - fhir
    - hl7
    - nhs

# Would you like filenames to also be spellchecked?
spellcheck_filenames: true
```

During pull requests it will flag `fastify` and `fastify-plugin` as potential typos, even though it's in the array of excluded_words.
Example here: https://github.com/Fdawgs/fastify-disablecache/pull/2/checks?check_run_id=1687500011

**Comment by MikeRogers0** [comment]
@Fdawgs - Is this for the `TypoCI/spellcheck-action` or the [GitHub Marketplace app](https://github.com/marketplace/typo-ci)?

I haven't updated the GitHub marketplace App to look in `.github/.typo-ci.yml` yet (It is on my todo). I'll get on it this weekend :)

Though in the interim you don't need `javascript` in the dictionaries, it knows most programming languages methods. I think if you put this in `.typo-ci.yml` it should work.

```yml
dictionaries:
    - en
    - en_GB

# Any files/folders we should ignore?
excluded_files:
    - ".github/.typo-ci.yml"
    - "node_modules/**/*"
    - "yarn.lock"

# Any typos we should ignore?
excluded_words:
    - fastify
    - fhir
    - hl7
    - nhs

# Would you like filenames to also be spellchecked?
spellcheck_filenames: true
```
